Enha: Added product count for each language on vendor dashboad
weDevsOfficial/dokan-wpml pull request #17
Opened 2021-10-11 06:39 UTC by shahadat015

WooCommerce WPML handles product translation by creating a product for each language. For that reason, the Dokan vendor dashboard shows product count for all, online and in stock including translated products. I have added also counts for each language on the vendor dashboard.

You have to add this line before end `</ul>` tag of file `dokan-lite/templates/products/listing-status-filter.php`
`<?php do_action( 'dokan_after_product_listing_status_filter' ); ?>`

I have recorded a [short video](https://drive.google.com/file/d/1FR70RgWdOcRbj4xH2HYueUfIAjqbZ9dg/view?usp=sharing). For my device problem voice was not recorded. I was shown how products count shows in the admin > products section. Then the vendor dashboard that I added. The problem was described here.

Fixes [#1366](https://github.com/weDevsOfficial/dokan/issues/1366)

2021-10-13 05:29 UTC, alamgircsebd requested changes

2021-10-13 05:29 UTC, alamgircsebd commented on Dokan_Wpml_Products_Count.php
> + * @since 1.0.5
use since `1.0.7`

2021-10-13 05:29 UTC, alamgircsebd commented on Dokan_Wpml_Products_Count.php
> +     * Constructor for Dokan_Wpml_Products_Count class
use since

2021-10-13 05:29 UTC, alamgircsebd commented on Dokan_Wpml_Products_Count.php
> +     * @since 1.0.5
use since `1.0.7`

2021-10-13 05:29 UTC, alamgircsebd commented on Dokan_Wpml_Products_Count.php
> +     * Language wise product count
replace by `Language wise products count`

2021-10-13 05:29 UTC, alamgircsebd commented on dokan-wpml.php
> +     *  @since 1.0.5
check all since above mentioned

2021-10-13 05:56 UTC, shahadat015 commented on dokan-wpml.php
> +     *  @since 1.0.5
@alamgircsebd I have added a new commit with request changes.

2021-10-18 15:22 UTC, shahadat015 commented on Dokan_Wpml_Products_Count.php
> +                    "SELECT language_code, COUNT(posts.ID) AS count FROM wp_icl_translations translations
Added prefix for wp_icl_translations  table.

2021-10-18 15:29 UTC, shahadat015 commented on Dokan_Wpml_Products_Count.php
> +        foreach ( $counts as $count ) {
I recorded a [short video]( https://drive.google.com/file/d/1FR70RgWdOcRbj4xH2HYueUfIAjqbZ9dg/view?usp=sharing). For my device microphone problem voice was not recorded. I was showed how products count shows in the admin > products section. Then the vendor dashboard that I added. The problem was [described here](https://github.com/weDevsOfficial/dokan/issues/1366).

2021-12-30 10:22 UTC, shahadat015 commented
Don't need to add count now

2021-12-30 10:22 UTC, closed without merging